"""fase2_instructors_classes_attendance_graduation

Revision ID: cec4d1fe0f70
Revises: 6c38ac9bcd61
Create Date: 2026-06-02 20:52:57.356615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cec4d1fe0f70'
down_revision: Union[str, None] = '6c38ac9bcd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belt_levels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('instructors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructors_name'), 'instructors', ['name'], unique=False)
    op.create_table('class_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graduation_events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graduation_events_event_date'), 'graduation_events', ['event_date'], unique=False)
    op.create_table('private_classes',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_classes_scheduled_at'), 'private_classes', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_private_classes_student_id'), 'private_classes', ['student_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_group_id', sa.UUID(), nullable=True),
    sa.Column('private_class_id', sa.UUID(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('check_in_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['private_class_id'], ['private_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_check_in_at'), 'attendance_records', ['check_in_at'], unique=False)
    op.create_index(op.f('ix_attendance_records_class_group_id'), 'attendance_records', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('class_enrollments',
    sa.Column('class_group_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_enrollments_class_group_id'), 'class_enrollments', ['class_group_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_student_id'), 'class_enrollments', ['student_id'], unique=False)
    op.create_table('class_schedules',
    sa.Column('class_group_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graduations',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('graduation_event_id', sa.UUID(), nullable=False),
    sa.Column('belt_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('fee_paid', sa.Boolean(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['belt_id'], ['belt_levels.id'], ),
    sa.ForeignKeyConstraint(['graduation_event_id'], ['graduation_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graduations_student_id'), 'graduations', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graduations_student_id'), table_name='graduations')
    op.drop_table('graduations')
    op.drop_table('class_schedules')
    op.drop_index(op.f('ix_class_enrollments_student_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_class_group_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_class_group_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_check_in_at'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_private_classes_student_id'), table_name='private_classes')
    op.drop_index(op.f('ix_private_classes_scheduled_at'), table_name='private_classes')
    op.drop_table('private_classes')
    op.drop_index(op.f('ix_graduation_events_event_date'), table_name='graduation_events')
    op.drop_table('graduation_events')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_instructors_name'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_table('belt_levels')
    # ### end Alembic commands ###
